package com.recep.hunt.model.notification

data class User(
    val country: String,
    val country_code: String,
    val created_at: String,
    val device_id: String,
    val device_token: String,
    val device_type: Any,
    val dob: String,
    val email: String,
    val email_verified_at: Any,
    val first_name: String,
    val for_bussiness: String,
    val for_date: Any,
    val for_friendship: Any,
    val gender: String,
    val id: Int,
    val is_notification_email: String,
    val is_notification_push: String,
    val is_online: String,
    val lang: Any,
    val last_name: String,
    val lat: Any,
    val mobile_no: String,
    val profile_pic: String,
    val referal_code: String,
    val reference_code: Any,
    val start_date: String,
    val status: String,
    val updated_at: String
)